# Generated by Django 4.0.3 on 2022-03-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='持ち物名を入力', max_length=20)),
                ('img', models.ImageField(default='', upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Pkmn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to=None)),
                ('name', models.CharField(help_text='ポケモン名を入力', max_length=20)),
                ('bigimg', models.ImageField(default='', upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('partyid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', help_text='著者名を入力', max_length=20)),
                ('twitterid', models.CharField(blank=True, help_text='TwitterIDを、"@"を含めた形で入力', max_length=100, null=True)),
                ('articletitle', models.CharField(default='記事名なし', help_text='記事のタイトルを入力', max_length=50)),
                ('season', models.IntegerField(default='816')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rule', models.CharField(choices=[('Single', 'シングル'), ('Double', 'ダブル')], max_length=10)),
                ('game', models.CharField(choices=[('SwSh', '剣盾'), ('SV', 'スカバイ')], max_length=10)),
                ('url', models.URLField(default='', max_length=1000)),
                ('partycheck', models.BooleanField(default=False)),
                ('item1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party_item1', to='rotoportal1.item')),
                ('item2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party_item2', to='rotoportal1.item')),
                ('item3', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party_item3', to='rotoportal1.item')),
                ('item4', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party_item4', to='rotoportal1.item')),
                ('item5', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party_item5', to='rotoportal1.item')),
                ('item6', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party_item6', to='rotoportal1.item')),
                ('pkmn1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party_pkmn1', to='rotoportal1.pkmn')),
                ('pkmn2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party_pkmn2', to='rotoportal1.pkmn')),
                ('pkmn3', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party_pkmn3', to='rotoportal1.pkmn')),
                ('pkmn4', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party_pkmn4', to='rotoportal1.pkmn')),
                ('pkmn5', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party_pkmn5', to='rotoportal1.pkmn')),
                ('pkmn6', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party_pkmn6', to='rotoportal1.pkmn')),
                ('tag1', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_tag1', to='rotoportal1.tag')),
                ('tag2', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_tag2', to='rotoportal1.tag')),
                ('tag3', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_tag3', to='rotoportal1.tag')),
                ('tag4', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_tag4', to='rotoportal1.tag')),
                ('tag5', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_tag5', to='rotoportal1.tag')),
                ('tag6', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_tag6', to='rotoportal1.tag')),
            ],
        ),
    ]
