# Generated by Django 4.0.3 on 2022-03-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotoportal1', '0002_alter_party_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkmn',
            name='bigimg',
            field=models.ImageField(blank=True, default='', null=True, upload_to=None),
        ),
    ]
