# Generated by Django 4.0.3 on 2022-03-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotoportal1', '0004_alter_party_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='rule',
            field=models.CharField(choices=[('single', 'シングル'), ('double', 'ダブル')], max_length=10),
        ),
    ]
